services:
  postgres:
    image: postgres:17
    container_name: postgres
    networks:
      - media-player-back-end
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
      POSTGRES_DB: media_player_db
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d/
      - ./docker/volumes/postgresql-data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    networks:
      - media-player-back-end
    ports:
      - "8080:8080"

networks:
  media-player-front-end:
    name: media-player-front-end
  media-player-back-end:
    name: media-player-back-end