services:
  postgres:
    image: postgres:17
    container_name: postgres
    networks:
      - media-player
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/volumes/postgres/initdb:/docker-entrypoint-initdb.d/
      - ./docker/volumes/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    networks:
      - media-player
    ports:
      - "8080:8080"
  redis:
    image: redis:7.4
    container_name: redis
    networks:
      - media-player
    ports:
      - ${REDIS_PORT}:6379
    environment:
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - ./docker/volumes/redis/data:/data
networks:
  media-player:
    name: media-player