services:
  postgres:
    image: postgres:17
    container_name: postgres
    networks:
      - media-player-back-end
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
      POSTGRES_DB: media_player_db
    volumes:
      - ./docker/volumes/postgres/initdb:/docker-entrypoint-initdb.d/
      - ./docker/volumes/postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    networks:
      - media-player-back-end
    ports:
      - "8080:8080"
  redis:
    image: redis:7.4
    container_name: redis
    networks:
      - media-player-back-end
    ports:
      - "6379:6379"
    environment:
      REDIS_USERNAME: default
      REDIS_HOST: redis
      REDIS_PASSWORD: redis
      REDIS_PORT: 6379
    volumes:
      - ./docker/volumes/redis/data:/data
networks:
  media-player-front-end:
    name: media-player-front-end
  media-player-back-end:
    name: media-player-back-end